### PR TITLE
Add protobuf, qt5-qtsvg, qt5-qttools

### PR DESCRIPTION
**Pull request by subpop**
Used by an upcoming flatpak I'm submitting, io.github.Cockatrice.cockatrice.

### CODE REVIEW

**Comment by TingPing** [comment]
The purpose of this repo is very commonly used libraries, you should bundle whatever you need in your own project for now unless there is wider use.

**Comment by subpop** [comment]
I figured these 3 libraries are common enough to be included in a repository like this. They don't add any baggage to app repositories that don't use them, and they do allow us to define a consistent version of, say, Qt5 across all apps in the repository. Either way, I'll pull protobuf into my app PR and out of this one.

**Comment by TingPing** [comment]
We base the usage on packages that already exist not ones that potentially will. AFAIK yours is the first to use these.

**Comment by subpop** [comment]
Ahhhh okay. That makes more sense.

**Pull request closed without merging**
