### PR TITLE
linux-audio: fluidsynth2 2.2.1

### PR DESCRIPTION
**Pull request by Eonfge**
Both dynamic and static

### CODE REVIEW

**Comment by Eonfge** [comment]
For your reference, I tested this with GZDoom. Not sure if that is enough testing for a shared module to be updated though, are there any hard rules on when shared-modules can get updated?

**Comment by TingPing** [comment]
> are there any hard rules on when shared-modules can get updated?

Not really. If its an API break then common sense applies.

One benefit to submodules is its very easy to hold back/revert an update in a project if an issue arises. At least temporarily.

**Comment by hfiguiere** [comment]
I'll test with the few audio apps later tonight. they are pretty good with API.

**Review by hfiguiere — APPROVED** [review]

**Comment by hfiguiere** [comment]
Thanks!

**Pull request merged**
