### PR TITLE
Add lua5.1

### PR DESCRIPTION
**Pull request by Unrud**
This time with a simplified build script in comparison to https://github.com/flathub/shared-modules/pull/60.

### CODE REVIEW

**Comment by TingPing** [comment]
Sorry if this was already discussed, but which packages use 5.1?

**Comment by Unrud** [comment]
> Sorry if this was already discussed, but which packages use 5.1?

  * https://github.com/flathub/net.openra.OpenRA
  * https://github.com/flathub/org.hedgewars.Hedgewars
  * https://github.com/flathub/uk.co.powdertoy.tpt

**Comment by TingPing** [comment]
Oh also is it OK if I mark you as the owner of this module (MRs will notify you)

**Comment by Unrud** [comment]
> Oh also is it OK if I mark you as the owner of this module

Yes.

**Pull request merged**
