### PR TITLE
Update lame to version 3.100

### PR DESCRIPTION
**Pull request by jakobjakobson13**
No tests have been done. So this update could break in the end some other programs that use lame.

### CODE REVIEW

**Comment by cheese** [comment]
lame-gtk1-ac-directives.patc and lame-ansi2knr2devnull.patch should have been applied upstream. Build tested on Sdk 18.08.

**Comment by cheese** [comment]
Patches still specified in json

**Comment by eszlari** [comment]
LAME is in the 18.08 runtime:
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/blob/18.08/elements/desktop/lame.bst

**Comment by jakobjakobson18** [comment]
> LAME is in the 18.08 runtime:
> https://gitlab.com/freedesktop-sdk/freedesktop-sdk/blob/18.08/elements/desktop/lame.bst

Sorry, for pushing this issue to an off topic direction, but actually there are also other things already provided by the [freedesktop-sdk](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/wikis/Release-Contents). To name them:
- [glew](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/blob/18.08/elements/extensions/glxinfo/glew.bst)
- [lame](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/blob/master/elements/desktop/lame.bst) (as eszlari already pointed out)
- [python2](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/blob/master/elements/base/python2.bst)
- [udev](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/blob/master/elements/desktop/libsystemd.bst) (apparently provided by [systemd](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/wikis/linux-system-notes)
-

**Comment by jurf** [comment]
python2 is only present in the SDK. Also, there’s still some apps not-yet-on 18.08 that use stuff from here.

**Comment by eszlari** [comment]
> glew

This is only there to compile `glxinfo`, the library is not in the runtime.

> udev

Not in the runtime, just take a look under:
`/var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/active/files`

**Comment by eszlari** [comment]
Since LAME is in runtime nowadays, this PR can be closed.

**Pull request closed without merging**
