### PR TITLE
Remove qt4

### PR DESCRIPTION
**Pull request by TingPing**
This hasn't been touched in over 3 years, nobody is an assigned maintainer, and a quick search on Github doesn't show a single package using it.

Since this is so complicated it likely doesn't even work anymore and is time to be removed.

### CODE REVIEW

**Comment by hfiguiere** [comment]
This packages uses it

https://github.com/flathub/org.scantailor.ScanTailor/blob/master/org.scantailor.ScanTailor.yaml#L19

**Comment by hfiguiere** [comment]
and it's built on 23.08

**Comment by TingPing** [comment]
Interesting that it still works. However if we have one user maybe it should be moved there. It really is just unmaintained here anyway.

**Comment by TingPing** [comment]
CC @Unrud

**Comment by Unrud** [comment]
I have no objection.

**Pull request merged**
