### PR TITLE
Add python3-yt-dlp

### PR DESCRIPTION
**Pull request by plata**

### CODE REVIEW

**Comment by plata** [comment]
CC @JBBgameich

**Comment by A6GibKm** [comment]
Could you provide a list of apps that use this module?

**Comment by plata** [comment]
I'm currently only aware of Plasmatube. Maybe @JBBgameich can provide more details on this version compared to the "regular" yt-dlp as used e.g. by io.mpv.Mpv.

**Comment by hfiguiere** [comment]
This is kinda out of scope for shared-modules.

**Comment by Erick555** [comment]
I think it may be too specific for shared-modules. Also I would call it just `yt-dlp` without python3 prefix

**Comment by Erick555** [comment]
I would call this just `yt-dlp` without python3 prefix. The thing that sucks here is the fact update bot doesn't work for shared-modules so for some apps switching to shared-module may be a step backward in maintenance flow (this thing updates very often).

**Comment by plata** [comment]
So just add it to Plasmatube locally?

**Comment by hfiguiere** [comment]
yes.

**Pull request closed without merging**
