### PR TITLE
Build GZDoom without Debug Info

### PR DESCRIPTION
**Pull request by Eonfge**
https://github.com/ZDoom/gzdoom/issues/2656

### CODE REVIEW

**Comment by Erick555** [comment]
Note that flatpak-builder will still apply -g -Wp,-D_GLIBCXX_ASSERTIONS from C/CXXFLAGS environment.

**Comment by cncz42** [comment]
I was about to comment the same discovery lol, doing a fresh build and relwithdebinfo alone doesn't trigger the crash. Looks like it was similar to the makepkg issue I had earlier, probably no need to remove the debug info although idk how it affects performance

**Comment by Erick555** [comment]
`Relwithdebinfo` shouldn't affect performance at all - it just add extra information to the binaries which is then stripped to separate extension. There is separate `Debug` mode which is the one that may affect perfromance.

https://github.com/ZDoom/gzdoom/blob/master/CMakeLists.txt#L153

**Comment by cncz42** [comment]
@Erick555 how would you go about overriding the default args via the manifest?

**Comment by Erick555** [comment]
one option is to set [CXXFLAGS](https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm18/blob/branch/23.08/org.freedesktop.Sdk.Extension.llvm18.json#L51)  env variable.

**Pull request merged**
