### PR TITLE
Added lua5.4

### PR DESCRIPTION
**Pull request by hfiguiere**
Darkatable needs it.

See https://github.com/flathub/org.darktable.Darktable/pull/81

### CODE REVIEW

**Comment by TingPing** [comment]
Please have somebody in `CODEOWNERS`

**Comment by hfiguiere** [comment]
tbf I know nothing about Lua. All I know is that Darktable was using 5.3 before and now require 5.4, so I thought it might be worth it.

**Comment by TingPing** [comment]
Small enough, I'll deal with it.

**Comment by hfiguiere** [comment]
thanks!

**Pull request merged**
