### PR TITLE
Update GZDoom to 4.7.0

### PR DESCRIPTION
**Pull request by Eonfge**

### CODE REVIEW

**Comment by Eonfge** [comment]
@hfiguiere Hey, I seem to miss the button to merge this change, although I'm code-owner of the file in question. Am I missing something?

**Comment by TingPing** [comment]
The code owner file is about organization of reviewers and does not grant commit access.

Though I have no problem granting it for regular contributors.

**Comment by Eonfge** [comment]
Thanks for merging.

As for giving me maintainer status, if you want to propose me to the other maintainers, then I'm certainly open to it. I can't make any promises about the amount of time and/or energy I got, but I'll gladly help you where I can.

**Comment by TingPing** [comment]
Invited you. Don't worry about activity, any help is appreciated :)

**Pull request merged**
