### PR TITLE
lua5.4: Fix json for liblua.so.5.4

### PR DESCRIPTION
**Pull request by ptitjano**

### CODE REVIEW

**Comment by hfiguiere** [comment]
Are you sure you are not confusing soname and version?

**Comment by ptitjano** [comment]
When I use current master on a flatpak application, I get this error: 

`Failed to open module: liblua.so.5.4: cannot open shared object file: No such file or directory`

I thought this change would fix the issue.

**Comment by JBBgameich** [comment]
I can confirm this patch allows running Ultrastar Deluxe on top of this shared-module

**Comment by hfiguiere** [comment]
thanks!

**Pull request merged**
