### PR TITLE
Added libsoup-2.4 (deprecated)

### PR DESCRIPTION
**Pull request by hfiguiere**
marking as draft but there are a few apps that still haven't been ported.

### CODE REVIEW

**Comment by hfiguiere** [comment]
Used with https://github.com/flathub/org.gnome.Recipes/pull/18

**Comment by TingPing** [comment]
I'm ok with this, do you know how many more modules need it?

**Comment by hfiguiere** [comment]
I thing Rhythmbox hasn't been ported yet. I'll look at it

GNOME-Games, but this is a deeper problem and the maintainer said he wanted to EOL it

I hope that we get rid of it. It's like clutter.

**Comment by hfiguiere** [comment]
https://github.com/flathub/org.gnome.Rhythmbox3/pull/61

**Pull request merged**
