### PR TITLE
Add an external-data-checker workflow

### PR DESCRIPTION
**Pull request by orowith2os**
We'll need to figure out how to handle several manifests at once. Should there be a separate workflow for each, so that they can customize how often they run, such as if a module needs to update more often than another? Does the data checker allow several manifests as input?

Cc @TingPing

### CODE REVIEW

**Comment by TingPing** [comment]
If it is possible I think we should have a single workflow that checks all modules, then opens a separate PR for each module with updates (if a PR was not already opened).

I'm not super familiar with the data checker tool itself, it may need modifications.

**Comment by orowith2os** [comment]
I don't believe having one workflow check all manifests and open one PR for each manifest is possible... But maybe the external-data-checker folks can figure something out?

**Comment by TingPing** [comment]
It would probably involve some custom scripts, but I think an action can use the Github API however it wishes.

**Comment by orowith2os** [comment]
I'll set up a custom workflow based on the data checker at some point. 

It's going to involve setting all the manifests to check inside of a file and running a script that goes through that file. This is probably the cleanest solution. I might also set up a build workflow to be sure everything works correctly.

**Comment by orowith2os** [comment]
Going to pick this up again, but use a more custom workflow. The one we normally use on apps isn't suitable here.

**Comment by orowith2os** [comment]
See https://github.com/flathub/shared-modules/pull/250

**Pull request closed without merging**
